#!/usr/bin/env bash
# Render a pitty scenario, substituting the run's nonce for __PGW_NONCE__.
#
# Why this exists: pitty v1.2.2 interpolates ${VAR} in `spawn` and `send` but not
# inside an `expect` block, so a scenario that sends the nonce and then asserts
# on `ACK ${PGW_NONCE}` compares against those literal characters and can never
# match. Rendering the file first puts the run's actual nonce on both sides, so
# the assertion tests the round trip it claims to test.
#
# Prints the rendered path on stdout; the caller runs pitty against it.
set -euo pipefail

scenario="${1:?usage: render-scenario.sh <scenario.yaml> <out-dir>}"
out_dir="${2:?usage: render-scenario.sh <scenario.yaml> <out-dir>}"
: "${PGW_NONCE:?PGW_NONCE must be exported by the calling recipe}"

# The nonce is generated by the recipe as [A-Z]{10} with a PGW prefix. Rejecting
# anything else keeps a stray value from being spliced into the scenario, and
# keeps sed's replacement text free of characters it would treat as syntax.
if [[ ! "${PGW_NONCE}" =~ ^PGW[A-Z]+$ ]]; then
  echo "PGW_NONCE must match ^PGW[A-Z]+$ (got a value of length ${#PGW_NONCE})" >&2
  exit 1
fi

rendered="${out_dir}/$(basename "${scenario}")"
sed "s/__PGW_NONCE__/${PGW_NONCE}/g" "${scenario}" >"${rendered}"

# Fail loudly rather than silently running an unrendered scenario: a marker left
# behind would make the assertion compare against the literal placeholder, which
# is the very failure mode this script exists to remove.
if grep -q '__PGW_NONCE__' "${rendered}"; then
  echo "render failed: __PGW_NONCE__ still present in ${rendered}" >&2
  exit 1
fi

echo "${rendered}"
