/**
 * Generated by `scripts/generate_attestation_digests.mjs`. Do not edit.
 *
 * SHA-256 of the attester source and of the Attested Computation document, fixed
 * at build time so the production image — which ships only `dist/` — can still
 * name the bytes a third party must fetch to replay the verdict.
 *
 * Run `pnpm --filter @privacy-gateway/common build` to regenerate. The build
 * fails if this file is out of sync with the sources it names.
 *
 * The line wrapping below is oxfmt's: a 64-character literal plus the
 * declaration exceeds the print width, so the formatter breaks after `=`.
 * Emitting it pre-wrapped keeps `--check` a fixed point under `just fmt`.
 */

/** SHA-256 of `packages/common/src/attesters/leak_check.ts`. */
export const ATTESTER_SHA256_BUILD =
  '8b427a667e6426be7061777d8c7952e57a816b8fbcd0410fdafea2e737529ce9';

/** SHA-256 of `knowledge/computations/leak-check.md`. */
export const COMPUTATION_SHA256_BUILD =
  '818736ce10622a56801d848aab46485afa87e91ee7a5dfffb8f193efc135efc0';
