#!/usr/bin/env node
/**
 * Emit `src/attestation_digests.generated.ts` from the bytes it names.
 *
 * Runs as part of `pnpm --filter @privacy-gateway/common build`, before `tsc`,
 * so the compiled `dist/` carries the two SHA-256 digests as constants. The
 * production Synthesis image copies only `dist/`, and hashing a `.ts` file that
 * is not in the image produced the literal string `unavailable` — a digest that
 * cannot be replayed while the document still claimed machine confirmation.
 *
 * Why not copy the sources into the runtime image instead: the image would then
 * carry two copies of the attester that could drift, and every consumer of the
 * digest would have to agree on which copy is canonical. A constant fixed at
 * build time has exactly one answer, and `--check` keeps it honest.
 *
 * Usage:
 *   node scripts/generate_attestation_digests.mjs           # write
 *   node scripts/generate_attestation_digests.mjs --check   # verify in sync
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(here, '..');
const repoRoot = path.resolve(packageRoot, '../..');

/** The exact bytes each digest is taken over. Both must exist at build time. */
const SOURCES = {
  attester: path.join(packageRoot, 'src/attesters/leak_check.ts'),
  computation: path.join(repoRoot, 'knowledge/computations/leak-check.md'),
};

const OUTPUT = path.join(packageRoot, 'src/attestation_digests.generated.ts');

function digestOf(file) {
  return createHash('sha256').update(readFileSync(file)).digest('hex');
}

function render(attester, computation) {
  return `/**
 * Generated by \`scripts/generate_attestation_digests.mjs\`. Do not edit.
 *
 * SHA-256 of the attester source and of the Attested Computation document, fixed
 * at build time so the production image — which ships only \`dist/\` — can still
 * name the bytes a third party must fetch to replay the verdict.
 *
 * Run \`pnpm --filter @privacy-gateway/common build\` to regenerate. The build
 * fails if this file is out of sync with the sources it names.
 *
 * The line wrapping below is oxfmt's: a 64-character literal plus the
 * declaration exceeds the print width, so the formatter breaks after \`=\`.
 * Emitting it pre-wrapped keeps \`--check\` a fixed point under \`just fmt\`.
 */

/** SHA-256 of \`packages/common/src/attesters/leak_check.ts\`. */
export const ATTESTER_SHA256_BUILD =
  '${attester}';

/** SHA-256 of \`knowledge/computations/leak-check.md\`. */
export const COMPUTATION_SHA256_BUILD =
  '${computation}';
`;
}

const attester = digestOf(SOURCES.attester);
const computation = digestOf(SOURCES.computation);
const rendered = render(attester, computation);

if (process.argv.includes('--check')) {
  let current;
  try {
    current = readFileSync(OUTPUT, 'utf8');
  } catch {
    console.error(`attestation digests: ${OUTPUT} is missing; run the build to generate it`);
    process.exit(1);
  }
  if (current !== rendered) {
    console.error(
      'attestation digests: attestation_digests.generated.ts is out of sync with its sources; ' +
        'run `pnpm --filter @privacy-gateway/common build`',
    );
    process.exit(1);
  }
  console.log('attestation digests: in sync');
} else {
  writeFileSync(OUTPUT, rendered, 'utf8');
  console.log(
    `attestation digests: attester=${attester.slice(0, 12)} computation=${computation.slice(0, 12)}`,
  );
}
